spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctiondb
    username: auction
    password: auction
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      write-dates-as-timestamps: false
